---
postgres:
  user: postgres
  password: postgres
  host: localhost
  port: 5432
  db_name: ray_app
  echo: True
  autoflush: False


redis:
  host: localhost
  port: 6379


weather_api:
  api_key: f7c0e81d090f774156744441415fde77