"""add tables

Revision ID: 568612e7b9da
Revises: d7e5bb31647b
Create Date: 2023-12-04 16:33:21.625685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "568612e7b9da"
down_revision: Union[str, None] = "d7e5bb31647b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "confirmed")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("confirmed", sa.BOOLEAN(), server_default=sa.text("false"), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
